### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by 0xisk** [urw7rs/spiralpp#2]
I'm getting the following error:
`zipfile.BadZipFile: File is not a zip file`

And I followed the following steps: 

First I installed their docker image by this command: 

```bash
docker run -it -p 8888:8888 urw7rs/spiralpp:latest /bin/bash
```

And here is the output of `ls` from inside the Docker image:

```bash
(spiralpp) root@8c0404e74c57:/src/spiralpp# ls
CODE_OF_CONDUCT.md  
LICENSE    
dataset.lock   
libtorchbeast.egg-info  
pyproject.toml    
setup.py     
third_party
CelebAMask-HQ       
README.md  
demo.ipynb     
nest                    
requirements.txt  
spiral-envs  
torchbeast
Dockerfile          
build      
libtorchbeast  
plot.ipynb              
scripts           
tests
```

And then after running this command: 

```bash
python -m torchbeast.polybeast \
     --dataset celeba-hq \
     --env_type libmypaint \
     --canvas_width 64 \
     --use_pressure \
     --use_tca \
     --num_actors 64 \
     --total_steps 30000000 \
     --policy_learning_rate 0.0004 \
     --entropy_cost 0.01 \
     --batch_size 64 \
     --episode_length 40 \
     --xpid example
```

I got the following error: 

```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/spiralpp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/spiralpp/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/spiralpp/torchbeast/polybeast.py", line 59, in <module>
    main()
  File "/src/spiralpp/torchbeast/polybeast.py", line 52, in main
    run_learner(flags)
  File "/src/spiralpp/torchbeast/polybeast.py", line 31, in run_learner
    polybeast_learner.main(flags)
  File "/src/spiralpp/torchbeast/polybeast_learner.py", line 865, in main
    train(flags)
  File "/src/spiralpp/torchbeast/polybeast_learner.py", line 585, in train
    dataset = utils.create_dataset(flags.dataset, grayscale)
  File "/src/spiralpp/torchbeast/utils.py", line 88, in create_dataset
    dataset = CelebAHQ(root="./", split="train", transform=tsfm, download=True)
  File "/src/spiralpp/torchbeast/core/datasets.py", line 53, in __init__
    self.download()
  File "/src/spiralpp/torchbeast/core/datasets.py", line 122, in download
    os.path.join(self.root, self.base_folder, "CelebAMask-HQ.zip"), "r"
  File "/root/miniconda3/envs/spiralpp/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/root/miniconda3/envs/spiralpp/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

The error is coming from [/src/spiralpp/torchbeast/core/datasets.py][2] line 122: 

```python
with zipfile.ZipFile(
            os.path.join(self.root, self.base_folder, "CelebAMask-HQ.zip"), "r"
        ) as f:
            f.extractall(os.path.join(self.root, self.base_folder))
```

And here is the output of `ls` from inside the `CelebAMask-HQ` directory:

```bash
(spiralpp) root@8c0404e74c57:/src/spiralpp/CelebAMask-HQ# ls
CelebAMask-HQ.zip  
list_eval_partition.txt
```

  [1]: https://github.com/urw7rs/spiralpp
  [2]: https://github.com/urw7rs/spiralpp/blob/master/torchbeast/core/datasets.py

**Comment by 0xisk** [comment]
Hi @urw7rs, @heiner could you please help me to solve this issue?

**Comment by urw7rs** [comment]
CelebaHQ sometimes can't download the files from google drive. This is a [known issue](https://github.com/pytorch/vision/issues/2262). Try downloading the file manually and set download=False at [https://github.com/urw7rs/spiralpp/blob/6f1d6130e99cb44f8dbc4c0e291f194f3f84a12c/torchbeast/utils.py#L84](spiralpp/torchbeast/utils.py) line 84.

**Comment by iskanderandrews** [comment]
Alright @urw7rs so I downloaded the dataset manually from here: https://github.com/switchablenorms/CelebAMask-HQ
And now running this command: 
```bash
python -m torchbeast.polybeast \
     --dataset celeba-hq \
     --env_type libmypaint \
     --canvas_width 64 \
     --use_pressure \
     --use_tca \
     --num_actors 64 \
     --total_steps 30000000 \
     --policy_learning_rate 0.0004 \
     --entropy_cost 0.01 \
     --batch_size 64 \
     --episode_length 40 \
     --xpid example
```

But I need your advice here: 
What do you think is preferable to run this image on the cloud or it's okay to run it locally in my machine? 
My machine resources: 

- RAM Type: DDR4 SO-DIMM
- RAM Size : 16 GB
- Processor Speed (GHz): 2.9 GHz
- Graphics: 6 GB NVIDIA GeForce RTX 2060

And what could be the expected time for the model building according to these ressouces? 
Thank you in advance!
